### ISSUE TITLE
Enhancement: enable Shield authentication

### ISSUE THREAD

**Issue by infodavidgit** [WedjaaOpen/ElasticSearchOSGI#5]
Hi,

To improve maintainability, you could use the maven-bundle-plugin to build an OSGI archive.

Best regards

**Comment by Wedjaa** [comment]
Look into the development branch. I have implemented maven-bundle-plugin based OSGI bundle creation. I am currently testing it before moving it in the master branch.

**Comment by ghost** [comment]
Hi,

Great job.

Thanks a lot

Best regards,
david

**Comment by Wedjaa** [comment]
Implemented Shield authentication and included the new OSGI bundle - with Shield plugin - in the repo.
