### ISSUE TITLE
Shield for user authentication

### ISSUE THREAD

**Issue by infodavidgit** [WedjaaOpen/ElasticSearchOSGI#6]
Hi,

Please, could you add the jar of the following artifact into the bundle ? This one is required for authentication.
```
<dependency>
  <groupId>org.elasticsearch.plugin</groupId>
  <artifactId>shield</artifactId>
  <version>2.2.0</version>
</dependency>
```

If necessary, you can add the repository of Elasticsearch by adding the following elements into the POM:
```
<repositories>
  <!-- add the elasticsearch repo -->
  <repository>
    <id>elasticsearch-releases</id>
    <url>https://maven.elasticsearch.org/releases</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
</repositories>
```

Thanks,

Best regards,
david

**Comment by Wedjaa** [comment]
Will look into enabling Shield integration for the next release.

**Comment by ghost** [comment]
Thanks a lot, for sure one of the two enhancements can be closed.

When do you plan the delivery of the next release ?

Best regards,
david

**Comment by Wedjaa** [comment]
Working on  publishing the new version (2.3.0) as we speak.

**Comment by Wedjaa** [comment]
Released both in the GIT repo and on the plugins site - see ElasticJasperSite for info.
